version: 2

jobs:
  build_and_test:
    machine:
      image: circleci/classic:201808-01
    working_directory: ~/dbt-amzn
    steps:
      - checkout
      - run: 
          name: Build Docker image
          command: |
            docker build -t slalombuild/dbt-amzn .
      - run: 
          name: Test Docker image
          command: |
            docker run slalombuild/dbt-amzn dbt --version 2>&1|grep 'Up to date'
      - run: 
          name: Verify image size
          command: |
            docker images | grep slalombuild/dbt-amzn | grep 'MB$'
      # - run:
      #     name: "Set Python version"
      #     command: pyenv global 3.7.0
      # - run: 
      #     name: Run Python tests
      #     command: |
      #       pip install --upgrade pip
      #       pip install -r requirements-dev.txt
      #       tox
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
